sudo: false
language: node_js
node_js:
  - "17"
  - "16"
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js